name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  SEARCH_ENGINE_URL: ${{ secrets.SEARCH_ENGINE_URL }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
  upload:
    needs: [deploy]
    name: Upload receipts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - ./HowToCook/dishes/aquatic
          - ./HowToCook/dishes/breakfast
          - ./HowToCook/dishes/condiment
          - ./HowToCook/dishes/dessert
          - ./HowToCook/dishes/drink
          - ./HowToCook/dishes/meat_dish
          - ./HowToCook/dishes/semi-finished
          - ./HowToCook/dishes/soup
          - ./HowToCook/dishes/staple
          - ./HowToCook/dishes/template
          - ./HowToCook/dishes/vegetable_dish
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.22.2
      - run: |
          deno run --allow-all ./main.ts \
            --url="${{ env.SEARCH_ENGINE_URL }}" \
            --path="${{ matrix.path }}"
